include:
  - ../base.yml

services:
  receiver:
    tty: true
    command: sh -c "sh rules.sh && ./timeshifter 1 2000 3000"
    cap_add:
      - NET_ADMIN
    stop_grace_period: 1s
    network_mode: service:receiver_base
    build:
      dockerfile_inline: |
        FROM gcc:12.4
        RUN git clone https://github.com/anfractuosity/timeshifter.git
        WORKDIR timeshifter
        RUN apt update && apt install -y libnetfilter-queue-dev iptables inetutils-ping
        RUN gcc -O2 -lnetfilter_queue -lnfnetlink -lm -o ./timeshifter timeshifter.c

        COPY <<EOF ./rules.sh
          iptables -F
          iptables -A OUTPUT -p icmp --icmp-type echo-request -j NFQUEUE --queue-num 0
          iptables -A INPUT -p icmp --icmp-type echo-reply -j NFQUEUE --queue-num 1
        EOF

  sender:
    extends: receiver
    network_mode: service:sender_base
    depends_on:
      - receiver
    command: sh -c "sh rules.sh && ping 10.88.88.8& echo "HELLO" | ./timeshifter 0 2000 3000"
